/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface NetworkApi {
	networkExit: (request: Api.NetworkExitRequest) => Promise<NetworkExitResponse>
	networkJoin: (request: Api.NetworkJoinRequest) => Promise<NetworkJoinResponse>
	networkList: (request: Api.NetworkListRequest) => Promise<NetworkListResponse>
}

export type NetworkExitResponse = NetworkExit200Response | NetworkExitDefaultResponse

export interface NetworkExit200Response {
	status: 200
	body: Api.NetworkExitResponse
	headers?: never
}

export interface NetworkExitDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type NetworkJoinResponse = NetworkJoin200Response | NetworkJoinDefaultResponse

export interface NetworkJoin200Response {
	status: 200
	body: Api.NetworkJoinResponse
	headers?: never
}

export interface NetworkJoinDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type NetworkListResponse = NetworkList200Response | NetworkListDefaultResponse

export interface NetworkList200Response {
	status: 200
	body: Api.NetworkListResponse
	headers?: never
}

export interface NetworkListDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

