/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface MessageApi {
	messageCount: (request: Api.CorrectionCountRequest) => Promise<MessageCountResponse>
	messageList: (request: Api.CorrectionMessageListRequest) => Promise<MessageListResponse>
	messageListBy: (request: Api.CorrectionListByRequest) => Promise<MessageListByResponse>
	messageMarkAsRead: (request: Api.CorrectionMarkAsReadRequest) => Promise<MessageMarkAsReadResponse>
}

export type MessageCountResponse = MessageCount200Response | MessageCountDefaultResponse

export interface MessageCount200Response {
	status: 200
	body: Api.CorrectionCountResponse
	headers?: never
}

export interface MessageCountDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type MessageListResponse = MessageList200Response | MessageListDefaultResponse

export interface MessageList200Response {
	status: 200
	body: Api.CorrectionMessageListResponse
	headers?: never
}

export interface MessageListDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type MessageListByResponse = MessageListBy200Response | MessageListByDefaultResponse

export interface MessageListBy200Response {
	status: 200
	body: Api.CorrectionListByResponse
	headers?: never
}

export interface MessageListByDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type MessageMarkAsReadResponse = MessageMarkAsRead200Response | MessageMarkAsReadDefaultResponse

export interface MessageMarkAsRead200Response {
	status: 200
	body: Api.CorrectionMarkAsReadResponse
	headers?: never
}

export interface MessageMarkAsReadDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

