/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface VectorApi {
	vectorQuery: (request: Api.VectorVectorRequest) => Promise<VectorQueryResponse>
}

export type VectorQueryResponse = VectorQuery200Response | VectorQueryDefaultResponse

export interface VectorQuery200Response {
	status: 200
	body: Api.VectorVectorResponse
	headers?: never
}

export interface VectorQueryDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

