/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express, Request, Response } from 'express'
import passport from 'passport'
import multer from 'multer'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.AssetApi) {
	app.post(
		'/api/v1/asset/delete',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetDeleteAssetRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.assetDelete(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetDeleteAssetResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in asset.assetDelete', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in asset.assetDelete', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in asset.assetDelete', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/asset/detail',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetAssetDetailRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.assetDetail(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetAssetDetailResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in asset.assetDetail', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in asset.assetDetail', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in asset.assetDetail', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/asset/search',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetSearchAssetRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.assetSearch(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetSearchAssetResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in asset.assetSearch', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in asset.assetSearch', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in asset.assetSearch', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/asset/sign',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetSignAssetRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.assetSign(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetSignAssetResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in asset.assetSign', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in asset.assetSign', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in asset.assetSign', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/asset/update',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetUpdateAssetRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.assetUpdate(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetUpdateAssetResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in asset.assetUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in asset.assetUpdate', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in asset.assetUpdate', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

}
