/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface AssetApi {
	assetDelete: (request: Api.AssetDeleteAssetRequest) => Promise<AssetDeleteResponse>
	assetDetail: (request: Api.AssetAssetDetailRequest) => Promise<AssetDetailResponse>
	assetSearch: (request: Api.AssetSearchAssetRequest) => Promise<AssetSearchResponse>
	assetSign: (request: Api.AssetSignAssetRequest) => Promise<AssetSignResponse>
	assetUpdate: (request: Api.AssetUpdateAssetRequest) => Promise<AssetUpdateResponse>
}

export type AssetDeleteResponse = AssetDelete200Response | AssetDeleteDefaultResponse

export interface AssetDelete200Response {
	status: 200
	body: Api.AssetDeleteAssetResponse
	headers?: never
}

export interface AssetDeleteDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type AssetDetailResponse = AssetDetail200Response | AssetDetailDefaultResponse

export interface AssetDetail200Response {
	status: 200
	body: Api.AssetAssetDetailResponse
	headers?: never
}

export interface AssetDetailDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type AssetSearchResponse = AssetSearch200Response | AssetSearchDefaultResponse

export interface AssetSearch200Response {
	status: 200
	body: Api.AssetSearchAssetResponse
	headers?: never
}

export interface AssetSearchDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type AssetSignResponse = AssetSign200Response | AssetSignDefaultResponse

export interface AssetSign200Response {
	status: 200
	body: Api.AssetSignAssetResponse
	headers?: never
}

export interface AssetSignDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type AssetUpdateResponse = AssetUpdate200Response | AssetUpdateDefaultResponse

export interface AssetUpdate200Response {
	status: 200
	body: Api.AssetUpdateAssetResponse
	headers?: never
}

export interface AssetUpdateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

