/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface ApplicationApi {
	applicationCreate: (request: Api.ApplicationCreateApplicationRequest) => Promise<ApplicationCreateResponse>
	applicationDelete: (request: Api.ApplicationDeleteApplicationRequest) => Promise<ApplicationDeleteResponse>
	applicationDetail: (request: Api.ApplicationApplicationDetailRequest) => Promise<ApplicationDetailResponse>
	applicationSearch: (request: Api.ApplicationSearchApplicationRequest) => Promise<ApplicationSearchResponse>
}

export type ApplicationCreateResponse = ApplicationCreate200Response | ApplicationCreateDefaultResponse

export interface ApplicationCreate200Response {
	status: 200
	body: Api.ApplicationCreateApplicationResponse
	headers?: never
}

export interface ApplicationCreateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type ApplicationDeleteResponse = ApplicationDelete200Response | ApplicationDeleteDefaultResponse

export interface ApplicationDelete200Response {
	status: 200
	body: Api.ApplicationDeleteApplicationResponse
	headers?: never
}

export interface ApplicationDeleteDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type ApplicationDetailResponse = ApplicationDetail200Response | ApplicationDetailDefaultResponse

export interface ApplicationDetail200Response {
	status: 200
	body: Api.ApplicationApplicationDetailResponse
	headers?: never
}

export interface ApplicationDetailDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type ApplicationSearchResponse = ApplicationSearch200Response | ApplicationSearchDefaultResponse

export interface ApplicationSearch200Response {
	status: 200
	body: Api.ApplicationSearchApplicationResponse
	headers?: never
}

export interface ApplicationSearchDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

