/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface EventApi {
	eventConsume: (request: Api.EventConsumeRequest) => Promise<EventConsumeResponse>
	eventProduce: (request: Api.EventProduceRequest) => Promise<EventProduceResponse>
}

export type EventConsumeResponse = EventConsume200Response | EventConsumeDefaultResponse

export interface EventConsume200Response {
	status: 200
	body: Api.EventConsumeResponse
	headers?: never
}

export interface EventConsumeDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type EventProduceResponse = EventProduce200Response | EventProduceDefaultResponse

export interface EventProduce200Response {
	status: 200
	body: Api.EventProduceResponse
	headers?: never
}

export interface EventProduceDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

