/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express, Request, Response } from 'express'
import passport from 'passport'
import multer from 'multer'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.LinkApi) {
	app.post(
		'/api/v1/link/create',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetCreateLinkRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.linkCreate(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetCreateLinkResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in link.linkCreate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in link.linkCreate', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in link.linkCreate', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/link/detail',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetLinkDetailRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.linkDetail(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetLinkDetailResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in link.linkDetail', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in link.linkDetail', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in link.linkDetail', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/link/disable',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetDisableLinkRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.linkDisable(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetDisableLinkResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in link.linkDisable', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in link.linkDisable', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in link.linkDisable', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/link/search',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetSearchLinkRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.linkSearch(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetSearchLinkResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in link.linkSearch', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in link.linkSearch', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in link.linkSearch', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/link/update',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetUpdateLinkRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.linkUpdate(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetUpdateLinkResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in link.linkUpdate', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in link.linkUpdate', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in link.linkUpdate', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/link/visitor',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetLinkVisitorRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.linkVisitor(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetLinkVisitorResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in link.linkVisitor', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in link.linkVisitor', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in link.linkVisitor', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

}
