/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface LlmApi {
	llmComplete: (request: Api.LlmCompleteRequest) => Promise<LlmCompleteResponse>
	llmEdit: (request: Api.LlmEditRequest) => Promise<LlmEditResponse>
	llmGenerate: (request: Api.LlmGenerateRequest) => Promise<LlmGenerateResponse>
	llmSpeech: (request: Api.LlmSpeechRequest) => Promise<LlmSpeechResponse>
	llmTranslate: (request: Api.LlmTranslateRequest) => Promise<LlmTranslateResponse>
}

export type LlmCompleteResponse = LlmComplete200Response | LlmCompleteDefaultResponse

export interface LlmComplete200Response {
	status: 200
	body: Api.LlmComplete200Response
	headers?: never
}

export interface LlmCompleteDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type LlmEditResponse = LlmEdit200Response | LlmEditDefaultResponse

export interface LlmEdit200Response {
	status: 200
	body: Api.LlmEdit200Response
	headers?: never
}

export interface LlmEditDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type LlmGenerateResponse = LlmGenerate200Response | LlmGenerateDefaultResponse

export interface LlmGenerate200Response {
	status: 200
	body: Api.LlmGenerate200Response
	headers?: never
}

export interface LlmGenerateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type LlmSpeechResponse = LlmSpeech200Response | LlmSpeechDefaultResponse

export interface LlmSpeech200Response {
	status: 200
	body: Api.LlmSpeechResponse
	headers?: never
}

export interface LlmSpeechDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type LlmTranslateResponse = LlmTranslate200Response | LlmTranslateDefaultResponse

export interface LlmTranslate200Response {
	status: 200
	body: Api.LlmTranslateResponse
	headers?: never
}

export interface LlmTranslateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

