/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface NamespaceApi {
	namespaceCreate: (request: Api.AssetCreateNamespaceRequest) => Promise<NamespaceCreateResponse>
	namespaceDelete: (request: Api.AssetDeleteNamespaceRequest) => Promise<NamespaceDeleteResponse>
	namespaceDetail: (request: Api.AssetNamespaceDetailRequest) => Promise<NamespaceDetailResponse>
	namespaceSearch: (request: Api.AssetSearchNamespaceRequest) => Promise<NamespaceSearchResponse>
	namespaceUpdate: (request: Api.AssetUpdateNamespaceRequest) => Promise<NamespaceUpdateResponse>
}

export type NamespaceCreateResponse = NamespaceCreate200Response | NamespaceCreateDefaultResponse

export interface NamespaceCreate200Response {
	status: 200
	body: Api.AssetCreateNamespaceResponse
	headers?: never
}

export interface NamespaceCreateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type NamespaceDeleteResponse = NamespaceDelete200Response | NamespaceDeleteDefaultResponse

export interface NamespaceDelete200Response {
	status: 200
	body: Api.AssetDeleteNamespaceResponse
	headers?: never
}

export interface NamespaceDeleteDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type NamespaceDetailResponse = NamespaceDetail200Response | NamespaceDetailDefaultResponse

export interface NamespaceDetail200Response {
	status: 200
	body: Api.AssetNamespaceDetailResponse
	headers?: never
}

export interface NamespaceDetailDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type NamespaceSearchResponse = NamespaceSearch200Response | NamespaceSearchDefaultResponse

export interface NamespaceSearch200Response {
	status: 200
	body: Api.AssetSearchNamespaceResponse
	headers?: never
}

export interface NamespaceSearchDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type NamespaceUpdateResponse = NamespaceUpdate200Response | NamespaceUpdateDefaultResponse

export interface NamespaceUpdate200Response {
	status: 200
	body: Api.AssetUpdateNamespaceResponse
	headers?: never
}

export interface NamespaceUpdateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

