/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface ContextApi {
	contextAdd: (request: Api.RagAddContextRequest) => Promise<ContextAddResponse>
	contextCreate: (request: Api.RagCreateContextRequest) => Promise<ContextCreateResponse>
	contextDelete: (request: Api.RagDeleteContextRequest) => Promise<ContextDeleteResponse>
	contextDeleteMessage: (request: Api.RagDeleteContextMessageRequest) => Promise<ContextDeleteMessageResponse>
}

export type ContextAddResponse = ContextAdd200Response | ContextAddDefaultResponse

export interface ContextAdd200Response {
	status: 200
	body: Api.RagAddContextResponse
	headers?: never
}

export interface ContextAddDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type ContextCreateResponse = ContextCreate200Response | ContextCreateDefaultResponse

export interface ContextCreate200Response {
	status: 200
	body: Api.RagCreateContextResponse
	headers?: never
}

export interface ContextCreateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type ContextDeleteResponse = ContextDelete200Response | ContextDeleteDefaultResponse

export interface ContextDelete200Response {
	status: 200
	body: Api.RagDeleteContextResponse
	headers?: never
}

export interface ContextDeleteDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type ContextDeleteMessageResponse = ContextDeleteMessage200Response | ContextDeleteMessageDefaultResponse

export interface ContextDeleteMessage200Response {
	status: 200
	body: Api.RagDeleteContextMessageResponse
	headers?: never
}

export interface ContextDeleteMessageDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

