/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface TopicApi {
	topicSearch: (request: Api.ApitopicSearchRequest) => Promise<TopicSearchResponse>
	topicSubscribe: (request: Api.TopicSubscribeRequest) => Promise<TopicSubscribeResponse>
	topicUnsubscribe: (request: Api.TopicUnsubscribeRequest) => Promise<TopicUnsubscribeResponse>
}

export type TopicSearchResponse = TopicSearch200Response | TopicSearchDefaultResponse

export interface TopicSearch200Response {
	status: 200
	body: Api.ApitopicSearchResponse
	headers?: never
}

export interface TopicSearchDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type TopicSubscribeResponse = TopicSubscribe200Response | TopicSubscribeDefaultResponse

export interface TopicSubscribe200Response {
	status: 200
	body: Api.TopicSubscribeResponse
	headers?: never
}

export interface TopicSubscribeDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type TopicUnsubscribeResponse = TopicUnsubscribe200Response | TopicUnsubscribeDefaultResponse

export interface TopicUnsubscribe200Response {
	status: 200
	body: Api.TopicUnsubscribeResponse
	headers?: never
}

export interface TopicUnsubscribeDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

