/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express, Request, Response } from 'express'
import passport from 'passport'
import multer from 'multer'
import * as t from './types'
import * as v from '../../validation'
import { Api } from '../../models'

export default function(app: Express, impl: t.BlockApi) {
	app.post(
		'/api/v1/block/confirm',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetConfirmBlockRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.blockConfirm(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetConfirmBlockResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in block.blockConfirm', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in block.blockConfirm', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in block.blockConfirm', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/block/get',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetGetBlockRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.blockGet(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetGetBlockResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in block.blockGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in block.blockGet', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in block.blockGet', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/block/put',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetPutBlockRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.blockPut(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiAssetPutBlockResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in block.blockPut', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in block.blockPut', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in block.blockPut', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/block/streamGet',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetStreamGetBlockRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.blockStreamGet(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiBlockStreamGet200ResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in block.blockStreamGet', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in block.blockStreamGet', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in block.blockStreamGet', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

	app.post(
		'/api/v1/block/streamPut',
		function (req: Request, res: Response) {
			try {
				function __body() {
					const __contentType = req.get('Content-Type')
					const __mimeType = __contentType ? __contentType.replace(/;.*/, '') : undefined

					if (__mimeType === 'application/json') {
						return v.modelApiAssetStreamPutBlockRequestFromRequest('body', req.body)
					}
					console.error(`Invalid request content type: ${__contentType}`)
					throw new Error(`Invalid request content type: ${__contentType}`)
				}

				impl.blockStreamPut(__body()).then(function (response) {
					if (response.status === 200) {
						let body: any
						try {
							body = v.modelApiBlockStreamPut200ResponseToResponse('response', response.body)
						} catch (error) {
							console.error('Invalid response body in block.blockStreamPut', error)
							res.status(500)
							res.send()
							return
						}

						res.status(200)
						res.type('application/json')
						res.send(body)
						return
					}

					/* Catch-all response */
					let body: any
					try {
						body = v.modelApiRpcStatusToResponse('response', response.body)
					} catch (error) {
						console.error('Invalid response body in block.blockStreamPut', error)
						res.status(500)
						res.send()
						return
					}

					res.status(response.actualStatus)
					res.send(body)
				}).catch(function (error) {
					console.error('Unexpected error in block.blockStreamPut', error.stack || error)
					res.status(500)
					res.send()
				})
			} catch (error) {
				/* Catch validation errors */
				res.status(400)
				res.type('text/plain; charset=utf-8')
				res.send(error)
			}
		}
	)

}
