/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface WalletApi {
	walletBalance: (request: Api.ContractBalanceRequest) => Promise<WalletBalanceResponse>
	walletCreateAddress: (request: Api.ContractCreateAddressRequest) => Promise<WalletCreateAddressResponse>
	walletTransaction: (request: Api.ContractTransactionRequest) => Promise<WalletTransactionResponse>
	walletWalletInfo: (request: Api.ContractWalletInfoRequest) => Promise<WalletWalletInfoResponse>
}

export type WalletBalanceResponse = WalletBalance200Response | WalletBalanceDefaultResponse

export interface WalletBalance200Response {
	status: 200
	body: Api.ContractBalanceResponse
	headers?: never
}

export interface WalletBalanceDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type WalletCreateAddressResponse = WalletCreateAddress200Response | WalletCreateAddressDefaultResponse

export interface WalletCreateAddress200Response {
	status: 200
	body: Api.ContractCreateAddressResponse
	headers?: never
}

export interface WalletCreateAddressDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type WalletTransactionResponse = WalletTransaction200Response | WalletTransactionDefaultResponse

export interface WalletTransaction200Response {
	status: 200
	body: Api.ContractTransactionResponse
	headers?: never
}

export interface WalletTransactionDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type WalletWalletInfoResponse = WalletWalletInfo200Response | WalletWalletInfoDefaultResponse

export interface WalletWalletInfo200Response {
	status: 200
	body: Api.ContractWalletInfoResponse
	headers?: never
}

export interface WalletWalletInfoDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

