/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface ConfigApi {
	configGet: (request: Api.ConfigGetConfigRequest) => Promise<ConfigGetResponse>
	configSet: (request: Api.ConfigSetConfigRequest) => Promise<ConfigSetResponse>
}

export type ConfigGetResponse = ConfigGet200Response | ConfigGetDefaultResponse

export interface ConfigGet200Response {
	status: 200
	body: Api.ConfigGetConfigResponse
	headers?: never
}

export interface ConfigGetDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type ConfigSetResponse = ConfigSet200Response | ConfigSetDefaultResponse

export interface ConfigSet200Response {
	status: 200
	body: Api.ConfigSetConfigResponse
	headers?: never
}

export interface ConfigSetDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

