/* eslint-disable */
// tslint:disable
/**
 * Yeying API
 * 
 *
 * OpenAPI spec version: 1.0
 * Contact: yeying.community@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator+.
 * https://github.com/karlvr/openapi-generator-plus
 * Do not edit the class manually.
 */

import { Express } from 'express'
import { Api } from '../../models'

export interface WarehouseApi {
	warehouseAdd: (request: Api.CorrectionAddWarehouseRequest) => Promise<WarehouseAddResponse>
	warehouseDetail: (request: Api.CorrectionDetailWarehouseRequest) => Promise<WarehouseDetailResponse>
	warehouseGetState: (request: Api.StoreGetStateRequest) => Promise<WarehouseGetStateResponse>
	warehouseList: (request: Api.CorrectionListWarehouseRequest) => Promise<WarehouseListResponse>
	warehouseTransfer: (request: Api.StoreTransferRequest) => Promise<WarehouseTransferResponse>
}

export type WarehouseAddResponse = WarehouseAdd200Response | WarehouseAddDefaultResponse

export interface WarehouseAdd200Response {
	status: 200
	body: Api.CorrectionAddWarehouseResponse
	headers?: never
}

export interface WarehouseAddDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type WarehouseDetailResponse = WarehouseDetail200Response | WarehouseDetailDefaultResponse

export interface WarehouseDetail200Response {
	status: 200
	body: Api.CorrectionDetailWarehouseResponse
	headers?: never
}

export interface WarehouseDetailDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type WarehouseGetStateResponse = WarehouseGetState200Response | WarehouseGetStateDefaultResponse

export interface WarehouseGetState200Response {
	status: 200
	body: Api.StoreGetStateResponse
	headers?: never
}

export interface WarehouseGetStateDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type WarehouseListResponse = WarehouseList200Response | WarehouseListDefaultResponse

export interface WarehouseList200Response {
	status: 200
	body: Api.CorrectionListWarehouseResponse
	headers?: never
}

export interface WarehouseListDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

export type WarehouseTransferResponse = WarehouseTransfer200Response | WarehouseTransferDefaultResponse

export interface WarehouseTransfer200Response {
	status: 200
	body: Api.StoreGetStateResponse
	headers?: never
}

export interface WarehouseTransferDefaultResponse {
	/* Catch-all response */
	status: 'default'
	actualStatus: number
	body: Api.RpcStatus
	headers?: never
}

